---
language: ruby
cache: bundler
script: bundle exec rake test
dist: trusty
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    sudo: required
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~>4.0"
  - rvm: 2.1.7
    sudo: required
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~>4.0"
  - rvm: 2.3.1
    sudo: required
    dist: trusty
    services: docker
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set="centos-7"
    script: bundle exec rake beaker
